### ISSUE TITLE
Can you write a tutorial for it?

### ISSUE THREAD

**Issue by streetartist** [CleanCut/rusty_engine#10]
It is a fantastic library.

Can you write a tutorial?

**Comment by CleanCut** [comment]
> It is a fantastic library.

Thank you! ❤️ 

> Can you write a tutorial?

I _sort of_ have written a tutorial, though not a proper here-all-the-features-of-the-engine one.  I have been (slowly) creating some [game scenarios](https://github.com/CleanCut/rusty_engine/tree/main/scenarios) for my students to use as prompts. The [Road Race scenario](https://github.com/CleanCut/rusty_engine/blob/main/scenarios/road_race.md) has a complete set of instructions which is _close_ to a tutorial.

We also have [the examples](https://github.com/CleanCut/rusty_engine/tree/main/examples). The example code covers most of the available features, and has a _little bit_ of explanation.

There is also the [library documentation](https://docs.rs/rusty_engine/latest/rusty_engine/), though I'll be the first to admit that so far (as of version 2.0.0) I've been sort of hit-and-miss on documenting things.

I still think it would be good to write a proper engine tutorial that walks through all the features of the engine, so I'll leave this issue open until I (or _someone_) gets around to it. I'd be more than happy accepting contributions if anyone would like to help out!  I have always intended to have a tutorial, and I even have a [placeholder](https://github.com/CleanCut/rusty_engine/tree/main/userguide) for it, in [mdBook](https://rust-lang.github.io/mdBook/) format.

**Comment by CleanCut** [comment]
There is now [A Rusty Engine Tutorial](https://cleancut.github.io/rusty_engine/)!!!

Resolved by #25 and #26
