### ISSUE TITLE
Consider use of GitHub Workflow for Rust tests

### ISSUE THREAD

**Issue by MAHDTech** [CleanCut/rusty_engine#3]
Hi!

Thanks for creating such a fun game engine! 🥳 

In an effort to set a consistent bar for contributions, would you consider adding a Workflow for Rust tests, rather than just relying on local Git hooks before contributing.

I've provided a sample here for consideration as a starting point 👉 #2

**Comment by MAHDTech** [comment]
☝️ Sponsor label 😍

**Comment by CleanCut** [comment]
Yay, it works on issues! 🥳  I accepted the pull request, so I'll go ahead and close this issue.
