### ISSUE TITLE
Feature List

### ISSUE THREAD

**Issue by CleanCut** [CleanCut/rusty_engine#4]
This issue is to hash out what features rusty_engine will ultimately support for version 1.0 -- we'll keep updating the list in this comment until we reach a good stopping point, and then transfer the list onto the readme.

Goal: Provide a fun, easy to use, minimalist, 2D game engine that works well to play with while learning Rust.
Not a goal: Being a commercially-viable game engine, or providing every possible feature.

Features
- [ ] Well-documented API
- [ ] Tutorial
- [ ] Examples
- [x] Graphics-accelerated window (currently OpenGL)
- [x] Input Presets
  - [x] Mouse
  - [x] Keyboard
- [ ] Provide a set of drawing primitives
  - [x] Images
  - [ ] Shapes (outline and filled)
    - [x] Circle
    - [x] Rectangle
    - [ ] Line
- [x] Audio
  - [x] Multi-channel
  - [x] Threaded
- [ ] Utilities
  - [x] Timer

To consider:
- Switch from `glium/glium` to either `gfx-rs/wgpu` or `amethyst/rendy` so we can use Metal/Vulkan/DirectX backends (and hopefully WASM support for free at some point) - this means a breaking rewrite of most of the engine, but it ensures a stable future (OpenGL is deprecated on macOS and will be removed at some point).
- Switch shapes to shaders - might be required if we make the above backend switch
- Alternately, punt on shapes by switching them to images, in which case shapes could be an asset pack
- Asset packs for sounds, images bundled with the engine.
- More configurable input mappings instead of only preset mappings
- Gamepad input
- Design that works well with an ECS (note that actually integrating an ECS is outside the scope
- Text rendering support

**Comment by CleanCut** [comment]
@MAHDTech Would you like to participate in determining the features for 1.0?

**Comment by MAHDTech** [comment]
@CleanCut, absolutely!

apologies for the delay, the notification seems to have gotten lost in an 🌊 of notifications.

I've got a weekend coming up without children so will have some free time to complete a certain '_space invaders_' training course. Hopefully I'll get more of a feeling for `rusty_engine` from there and be able to provide some better feedback. 😉

**Comment by CleanCut** [comment]
@MAHDTech A lot has happened in the last month!  I'm now a contributing member of [Amethyst](https://amethyst.rs/) and I'm working to make that successful.  With that in mind, I'm planning to put Rusty Engine on ice for the time being.  I'd still be happy brain-storming what it could become in the context to something built on top of Amethyst, if that sounds interesting to you.

**Comment by CleanCut** [comment]
> I've got a weekend coming up without children so will have some free time to complete a certain '_space invaders_' training course. Hopefully I'll get more of a feeling for `rusty_engine` from there and be able to provide some better feedback. 😉

I hope you enjoy the course, but I don't use Rusty Engine for it! 😄

**Comment by CleanCut** [comment]
Closing in favor of a new approach: wrapping an existing game engine in a simplified interface. See #9.

I would love collaborators if anyone is interested in participating!
