### ISSUE TITLE
Documentation typo / misattribution

### ISSUE THREAD

**Issue by steffahn** [CleanCut/rusty_engine#47]
Hi, I just noticed that these three fields have their documentation permuted incorrectly:

https://github.com/CleanCut/rusty_engine/blob/12a0d15b2940c3b438f3ac1d70e9204e9c1a5df0/src/game.rs#L83-L96

The field order seems decent, so I suppose the documentation should be moved to fix this.

**Comment by CleanCut** [comment]
Nice catch, thanks!
