### ISSUE TITLE
rusty-asteroids

### ISSUE THREAD

**Issue by etnt** [CleanCut/rusty_engine#49]
Hi,
Not sure if you are interested in see some "student work"...
Anyway, I wrote a little Asteroids game on top of rusty-engine.
I had a blast! Thanks for all your effort with it.

https://github.com/etnt/rusty-asteroids

Cheers, Toby

**Comment by CleanCut** [comment]
Rusty Asteroids is AWESOME!!! I love it!

Are you okay if I add a "Student Showcase" section to the Rusty Engine readme and link to it?

**Comment by etnt** [comment]
Hehe sure, feel free to do that :-)

**Comment by CleanCut** [comment]
Cool! I really want to encourage people to make little projects like this, and I think it will help inspire folks if they can see what others have done!

**Comment by CleanCut** [comment]
[Ta Da!](https://github.com/CleanCut/rusty_engine/blob/main/README.md#student-showcase)
