### ISSUE TITLE
Issue building cpal dependency

### ISSUE THREAD

**Issue by indraastra** [CleanCut/rusty_engine#58]
I'm following your (excellent) Ultimate Rust 2 course and just reached the game prototype stage, but immediately hit an issue when building a fresh project with only `rusty_engine` as a dependency. Here's my Cargo.toml file:

```
[package]
name = "tutorial"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusty_engine = "5.2.0"
```

Here are the abbreviated error logs:

```
error[E0308]: mismatched types
   --> /home//.cargo/registry/src/github.com-1ecc6299db9ec823/cpal-0.13.5/src/host/alsa/mod.rs:245:21
    |
244 |         let handle = match handle_result {
    |                            ------------- this expression has type `std::result::Result<host::alsa::alsa::PCM, (host::alsa::alsa::Error, host::alsa::alsa::nix::errno::Errno)>`
245 |             Err((_, nix::errno::Errno::EBUSY)) => return Err(BuildStreamError::DeviceNotAvailable),
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `host::alsa::alsa::nix::errno::Errno`, found enum `nix::errno::Errno`
    |
    = note: perhaps two different versions of crate `nix` are being used?

error[E0308]: mismatched types
   --> /home//.cargo/registry/src/github.com-1ecc6299db9ec823/cpal-0.13.5/src/host/alsa/mod.rs:246:21
    |
244 |         let handle = match handle_result {
    |                            ------------- this expression has type `std::result::Result<host::alsa::alsa::PCM, (host::alsa::alsa::Error, host::alsa::alsa::nix::errno::Errno)>`
245 |             Err((_, nix::errno::Errno::EBUSY)) => return Err(BuildStreamError::DeviceNotAvailable),
246 |             Err((_, nix::errno::Errno::EINVAL)) => return Err(BuildStreamError::InvalidArgument),
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `host::alsa::alsa::nix::errno::Errno`, found enum `nix::errno::Errno`
    |
    = note: perhaps two different versions of crate `nix` are being used?

error[E0308]: mismatched types
   --> /home//.cargo/registry/src/github.com-1ecc6299db9ec823/cpal-0.13.5/src/host/alsa/mod.rs:302:21
    |
301 |         let handle = match handle_result {
    |                            ------------- this expression has type `std::result::Result<&mut host::alsa::alsa::PCM, (host::alsa::alsa::Error, host::alsa::alsa::nix::errno::Errno)>`
302 |             Err((_, nix::errno::Errno::ENOENT)) | Err((_, nix::errno::Errno::EBUSY)) => {
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `host::alsa::alsa::nix::errno::Errno`, found enum `nix::errno::Errno`
    |
    = note: perhaps two different versions of crate `nix` are being used?
```

This also happens when depending *only* on `cpal = "0.14.0"`, so I know this is most likely some kind of issue with the dependency chain rather than `rusty_engine`, but I'm not familiar enough with Rust and cargo to be able to narrow it down much further. I'm able to build `cpal` from source, but not `rodio`, and no amount of futzing about with overridden/patched dependencies worked for me, so I'm completely at a loss. Apologies for laying this at your doorstep, but I figure you may be in a better position to get things building again.

I'm building using WSL2 on Windows with cargo version 1.64.0 (387270bc7 2022-09-16).

**Comment by CleanCut** [comment]
Have you [installed the Linux dependencies](https://github.com/CleanCut/rusty_engine/#linux-dependencies-including-wsl-2)?

**Comment by indraastra** [comment]
Yes, I was originally missing some of those dependencies but that resulted in more obvious error messages. Once I installed them, I began to see this issue with conflicting versions of the nix crate being pulled in by implicit dependencies (confirmed by running `cargo tree`).

**Comment by CleanCut** [comment]
🙁 Well that's not good. I'll see if I can get access to a Windows machine tonight, but I don't really use Windows, and I've never used WSL, so I'm going to be at a disadvantage debugging this.

If any Windows+WSL+Rust experts out there are reading this, I'd love some help figuring this out!

@indraastra What version of Windows are you using, specifically?

**Comment by CleanCut** [comment]
Oh! Just in case, please do a `cargo clean` and try building again and see if anything changes (just in case you need to have had a clean environment _after_ you installed the dependencies).

**Comment by indraastra** [comment]
@CleanCut I was wondering why this would be a Windows-specific issue so I tried to replicate this on Linux (specifically, Debian) and ran into the same issue:

```
❯ cargo check
...
error[E0308]: mismatched types
   --> .../.cargo/registry/src/github.com-1ecc6299db9ec823/cpal-0.13.5/src/host/alsa/mod.rs:803:40
    |
803 |             Err(err) if err.errno() == nix::errno::Errno::EPIPE => {
    |                                        ^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `host::alsa::alsa::nix::errno::Errno`, found enum `nix::errno::Errno`
    |
    = note: enum `nix::errno::Errno` and enum `host::alsa::alsa::nix::errno::Errno` have similar names, but are actually distinct types
note: enum `nix::errno::Errno` is defined in crate `nix`
   --> .../.cargo/registry/src/github.com-1ecc6299db9ec823/nix-0.23.1/src/errno.rs:774:5
...
For more information about this error, try `rustc --explain E0308`.
error: could not compile `cpal` due to 7 previous errors
```

```
❯ rustc --version
rustc 1.66.0-nightly (7fcf850d7 2022-10-23)

❯ cargo version
cargo 1.66.0-nightly (071eeaf21 2022-10-22)
```

This is right after doing a `rustup update` and starting from a new project with just this one dependency. It's strange because didn't think dependency hell was possible with how cargo managed multiple versions of a package :\

**Comment by CleanCut** [comment]
It appears this was [fixed yesterday upstream](https://github.com/RustAudio/cpal/pull/712) and released as cpal 0.14.1. 

You're getting cpal 0.13.5. Please try doing `cargo clean` and then `cargo update` and then building again! 🤞🏻

**Comment by dreyescat** [comment]
I tried the `cargo clean` and `cargo update` combo but it didn't work :cry:
Somewhere in the dependency tree `cpal` is "anchored" to `^0.13.0` and it is not updated to `0.14.1`.

I used [this suggested workaround](https://github.com/diwic/alsa-rs/issues/90#issuecomment-1288134557) in the meantime.

**Comment by indraastra** [comment]
Thanks for sharing the workaround @dreyescat! That did the trick for me, too. 

For anyone else reading, https://github.com/diwic/alsa-rs/issues/90#issuecomment-1288133983 is a nice summary of how this can happen despite multiple versions of a dependency being able to coexist.

**Comment by CleanCut** [comment]
Here is the workaround explicitly (so people don't have to follow through the links):

Add this line to the `[dependencies]` section of your `Cargo.toml` file:

```toml
alsa = "=0.6.0"
```

I'll leave this issue open until the upstream problem really goes away.

**Comment by CleanCut** [comment]
I believe the upstream problem has gone away.
