### ISSUE TITLE
wgpu-hal : Fails to compile

### ISSUE THREAD

**Issue by lightydo** [CleanCut/rusty_engine#62]
```
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

https://gist.github.com/lightydo/6b3a6fcb2f6c4b6f03eae7c2985af627

I tried this: https://github.com/bevyengine/bevy/blob/main/docs/linux_dependencies.md
but it did not help

**Comment by lightydo** [comment]
Fix: added `resolver="2"` to the top TOML file.

**Comment by CleanCut** [comment]
Yes! If you are using a workspace, you need to do that. 🤔 I should add that to a troubleshooting section or something...
