### ISSUE TITLE
Missing resource

### ISSUE THREAD

**Issue by tontm1981** [CleanCut/rusty_engine#64]
There is no image in `assets` folder, to use with `collider`application. Written tutorial (https://cleancut.github.io/rusty_engine/65-sprite-collider.html) has mentions to an image too, but no image was found in mentioned path.

**Comment by CleanCut** [comment]
You must [download the asset pack first](https://cleancut.github.io/rusty_engine/10-assets.html).  Please see the instructions on the linked page!
