### ISSUE TITLE
Compliation fails on MacOS

### ISSUE THREAD

**Issue by david-a-wheeler** [CleanCut/rusty_engine#65]
Attemping to compile this on MacOS fails, even after adding the undocumented argument in the TOML file:
~~~~
release = "2"
~~~~

Compile error follows.

~~~~
   Compiling wgpu-hal v0.12.5
error: DX12 API enabled on non-Windows OS. If your project is not using resolver="2" in Cargo.toml, it should.
  --> /Users/dwheeler/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-hal-0.12.5/src/lib.rs:53:1
   |
53 | compile_error!("DX12 API enabled on non-Windows OS. If your project is not using resolver=\"2\" in Cargo.toml, it should.");
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0432]: unresolved import `super::dx12`
  --> /Users/dwheeler/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-hal-0.12.5/src/lib.rs:68:20
   |
68 |     pub use super::dx12::Api as Dx12;
   |                    ^^^^ could not find `dx12` in the crate root
~~~~

**Comment by CleanCut** [comment]
Hmm...are you using a workspace? If so, [adding `resolver="2"` to your top-level Cargo.toml](https://github.com/CleanCut/rusty_engine/issues/62) may help.

- Which version of macOS?
- Which version of Rust?
- Which version of rusty_engine?

You need to be relatively near the latest version for all of the above.

**Comment by david-a-wheeler** [comment]
* MacOS: 10.15.7. There are many reports of external monitors failing on MacOS 11, and until recently some software I use didn't work on MacOS 11.
* Rust: 2021. The value edition = "2021" is in the TOML file. `rustc --version` reports rustc 1.67.0 (fc594f156 2023-01-24).
* rusty_engine: 4.0. The TOML file sets dependencies rusty_engine = "4.0". `cargo tree | grep rusty` shows v4.0.0.

**Comment by david-a-wheeler** [comment]
Entire contents of `Cargo.toml`:
~~~~
[package]
name = "tutorial"
version = "0.1.0"
edition = "2021"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusty_engine = "4.0"

[profile.dev]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
codegen-units = 16
~~~~

I ran `cargo build` first without `resolver = "2"`, that failed, I added that line and re-ran `cargo build`, it did not help.

**Comment by david-a-wheeler** [comment]
I should add that `cargo clean` followed by `cargo build` (with `resolver = "2"`) did not help.

**Comment by CleanCut** [comment]
The good news is it's quite possible that you'll be up and working with a simple version bump!

- You should definitely use `rusty_engine` `5.2.1` -- You can always manually [check for the latest version on crates.io](https://crates.io/crates/rusty_engine). I have also started recommending that people use `cargo add` to add dependencies, which will look up the latest version and add it to `Cargo.toml` for you. This will _probably_ get you working. If it doesn't...
- Try upgrading to Rust 1.67.1 (`rustup update`).
- And finally, if none of that works, then you need to update macOS. I would lean away from running unsupported versions that are no longer receiving security updates like 10.15:
<img width="981" alt="image" src="https://user-images.githubusercontent.com/5838512/218215041-45569241-5267-498a-900b-57481295f342.png">

**Comment by david-a-wheeler** [comment]
Updating `rusty_engine` and rust didn't help. I will eventually update the OS, however, I'm quite skeptical that will solve anything. It looks like the configuration system is using the Windows API on a non-Windows system. Is my setting of `resolver = "2"` in the right place, as a setting immediately in the top `[package]`? Should it be somewhere else?

Here are details of my attempts to resolve this, all not succeeding.

====

> You should definitely use rusty_engine 5.2.1 -- You can always manually [check for the latest version on crates.io](https://crates.io/crates/rusty_engine). I have also started recommending that people use cargo add to add dependencies, which will look up the latest version and add it to Cargo.toml for you. This will probably get you working. If it doesn't...

I normally use current libraries when making systems, but since I'm following your tutorial on Udemy I thought it'd be wiser to use exactly the same version. But updating is fine!

I updated to `rusty_engine` 5.2.1, no joy. Even more error messages during build with that. Sample below. Again, notice that it's trying to run the Windows API on a non-API system. That *should* fail, of course, but why is it trying to use the Windows-specific API?!? Here are some of its output.

~~~~
Compiling wgpu-hal v0.13.2
error: DX12 API enabled on non-Windows OS. If your project is not using resolver="2" in Cargo.toml, it should.
  --> /Users/dwheeler/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-hal-0.13.2/src/lib.rs:53:1
   |
53 | compile_error!("DX12 API enabled on non-Windows OS. If your project is not using resolver=\"2\" in Cargo.toml, it should.");
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0433]: failed to resolve: use of undeclared crate or module `winapi`
 --> /Users/dwheeler/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-hal-0.13.2/src/auxil/dxgi/conv.rs:1:5
  |
1 | use winapi::shared::dxgiformat;
  |     ^^^^^^ use of undeclared crate or module `winapi`

error[E0433]: failed to resolve: use of undeclared crate or module `winapi`
 --> /Users/dwheeler/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-hal-0.13.2/src/auxil/dxgi/conv.rs:5:9
  |
5 |     use winapi::shared::dxgiformat::*;
  |         ^^^^^^ use of undeclared crate or module `winapi`
~~~~


> Try upgrading to Rust 1.67.1 (rustup update).

I was already on 1.67.0, so I was skeptical that would help, but I tried anyway. I then ran cargo clean; cargo build. It didn't work, same basic problem.

~~~~
   Compiling wgpu-hal v0.13.2
error: DX12 API enabled on non-Windows OS. If your project is not using resolver="2" in Cargo.toml, it should.
  --> /Users/dwheeler/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-hal-0.13.2/src/lib.rs:53:1
   |
53 | compile_error!("DX12 API enabled on non-Windows OS. If your project is not using resolver=\"2\" in Cargo.toml, it should.");
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0433]: failed to resolve: use of undeclared crate or module `winapi`
 --> /Users/dwheeler/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-hal-0.13.2/src/auxil/dxgi/conv.rs:1:5
  |
1 | use winapi::shared::dxgiformat;
  |     ^^^^^^ use of undeclared crate or module `winapi`

error[E0433]: failed to resolve: use of undeclared crate or module `winapi`
 --> /Users/dwheeler/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-hal-0.13.2/src/auxil/dxgi/conv.rs:5:9
  |
5 |     use winapi::shared::dxgiformat::*;
  |         ^^^^^^ use of undeclared crate or module `winapi`

error[E0433]: failed to resolve: use of undeclared crate or module `winapi`
   --> /Users/dwheeler/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-hal-0.13.2/src/auxil/dxgi/conv.rs:143:9
    |
143 |     use winapi::shared::dxgiformat::*;
    |         ^^^^^^ use of undeclared crate or module `winapi`

error[E0433]: failed to resolve: use of undeclared crate or module `winapi`
 --> /Users/dwheeler/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-hal-0.13.2/src/auxil/dxgi/exception.rs:4:5
  |
4 | use winapi::{
  |     ^^^^^^ use of undeclared crate or module `winapi`

error[E0433]: failed to resolve: use of undeclared crate or module `winapi`
 --> /Users/dwheeler/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-hal-0.13.2/src/auxil/dxgi/factory.rs:1:5
  |
1 | use winapi::{
  |     ^^^^^^ use of undeclared crate or module `winapi`


~~~~



I don't like running an obsolete OS. However, I *require* an application that only just added support for MacOS 12+. At this point, my concern is that there have been *endless* external monitor problems with MacOS 12+. There are pages that list various attempts to fix them, e.g., <https://machow2.com/external-display-issues/>, but they aren't encouraging.

**Comment by david-a-wheeler** [comment]
BTW, thanks so much for responding so quickly. That's really appreciated, even if we can't solve it :-).

**Comment by CleanCut** [comment]
> BTW, thanks so much for responding so quickly. That's really appreciated, even if we can't solve it :-).

👍🏻 😄 No problem!

> Is my setting of `resolver = "2"` in the right place, as a setting immediately in the top `[package]`? Should it be somewhere else?

You should only need to do this in a _workspace_ `Cargo.toml`, in the `[workspace]` section. Are you [using a workspace](https://doc.rust-lang.org/cargo/reference/workspaces.html#virtual-workspace)? Are you, perhaps, inadvertently triggering a workspace by nesting a Rust project within another Rust project? Perhaps creating a new, blank project out somewhere where you are certain it's not inside another Rust project would help?

Putting that setting in the `[package]` section of a normal `Cargo.toml` doesn't hurt anything, but it also doesn't _do_ anything if you are using the 2021 edition.

**Comment by CleanCut** [comment]
> I don't like running an obsolete OS. However, I _require_ an application that only just added support for MacOS 12+. At this point, my concern is that there have been _endless_ external monitor problems with MacOS 12+. There are pages that list various attempts to fix them, e.g., https://machow2.com/external-display-issues/, but they aren't encouraging.

I hear you. I have had intermittent problems with a really cheap BenQ monitor I have, especially under MacOS 11 Big Sur (only occasional weirdness in later versions). All of my higher-quality monitors have been rock solid, though.

I would be absolutely thrilled if Apple pulled another Snow Leopard and did a release that focused only on stability and performance, rather than glitzy features and iOS-ifying that I don't care about!

**Comment by david-a-wheeler** [comment]
*Solved*, thank you, recreation in a completely different directory was the key step.

Regarding your comments...

> You should only need to do this in a workspace Cargo.toml, in the [workspace] section. Are you [using a workspace](https://doc.rust-lang.org/cargo/reference/workspaces.html#virtual-workspace)?

No, I just used `cargo new` which doesn't create a workspace.

> Are you, perhaps, inadvertently triggering a workspace by nesting a Rust project within another Rust project?

Not intentionally. I created a subdirectory called "tutorial" under $HOME/projects/ultimate_rust2/exercise/

> Perhaps creating a new, blank project out somewhere where you are certain it's not inside another Rust project would help?

Fair enough, and that resolved it:
~~~~
cd $HOME/project
cargo new tutorial_engine
cd tutorial_engine
# Set up Cargo.toml
cargo build
~~~~

Thanks again!

**Comment by CleanCut** [comment]
Aha! The `ultimate_rust2` repository itself is using a workspace! And it is configured to include anything inside the `exercise/` and `example/` directories in that workspace!

I've [added `resolver = "2"` to its workspace `Cargo.toml`](https://github.com/CleanCut/ultimate_rust2/blob/1b1ced37a428f0472be964a299ecfb1d81e0cc70/Cargo.toml) so that if in the future someone else happens to do the same thing, it won't break for them!
