### ISSUE TITLE
game setup

### ISSUE THREAD

**Issue by shautvast** [CleanCut/rusty_engine#69]
in your udemy course your code is like this

```rust
let mut game = new Game();
game.run();
```

I tried this and it didn't compile (error about something not implementing a Resource trait)

below is what is now the bare minimum to run the empty screen game

```rust
use rusty_engine::prelude::*;

#[derive(Resource)]
struct GameState {}

fn main() {
    let mut game = Game::new();
    let initial_game_state = GameState {};
    game.run(initial_game_state);
}
```

**Comment by CleanCut** [comment]
Yes, you are correct! I have updated the written documentation, and I need to update the video. I will do that soon!
