### ISSUE TITLE
Is there a way to detect collision for given two collider points of sprite

### ISSUE THREAD

**Issue by indiVar0508** [CleanCut/rusty_engine#71]
Hi

I am new to Rusty Engine and Rust in particular, recently started exploring it after your Rust intermediate course,

Was trying to write a logic and was wondering if there is a way to compute if two sprites are still colliding or not as it seems collisionEvent is generated once as collision happens for me i have some logic that i check after the event and if it still persists
i need to declare it as game over.

Do you have any suggestions for this or is there a public method available that takes two sprites and tells weather they are colliding or not.?

Thanks

**Comment by CleanCut** [comment]
Sure! You should be able to call [`Collider::colliding(sprite1, sprite2)`](https://docs.rs/rusty_engine/latest/rusty_engine/physics/enum.Collider.html#method.colliding) to check if two sprites are colliding.
