### ISSUE TITLE
embed assets to executable file

### ISSUE THREAD

**Issue by kuba-04** [CleanCut/rusty_engine#72]
Hello, thanks for this lib. It helped me to create a nice little educational game. But I don't know how to bundle this program into an executable. The game works for me from command line on mac, but I need to install it on other device for kids to use, the device will have either windows or android. First thing I did was to try embedding the assets into the bundle, but the lib doesn't allow me to use byt arrays in add_sprite() method (I wanted to use https://doc.rust-lang.org/std/macro.include_bytes.html macro as a first step). 
Do you have any advice how to proceed with this in order to run the game as executable file that includes everything in it? Should I try to extend your add_sprite to take byte arrays or it is not the best way? I am sure either you or someone else have come to this point already and solution is known

**Comment by CleanCut** [comment]
It is normal for executables on all platforms to require assets on disk in a specific place. If you place your executable in the same directory that contains the `assets` directory, I believe launching the game will Just Work™. 

`rusty_engine` is a simplification layer around a real game engine, called [Bevy](https://bevyengine.org/). AFAIK, Bevy does not currently support embedding assets into the binary, so it's not really an option for me to add without changing the upstream game engine. They might add that functionality in the future, though! If they do, then we could revisit this discussion! 😄
